# Project information
site_name: 'OpenAlgeria Documentation'
site_description: 'Documentation, Tutorial, Support'
site_author: 'Noureddine HADDAG'
site_url: 'https://social.openalgeria.org/@nhaddag'

# Repository
repo_name: 'OpenAlgeria/docs'
repo_url: 'https://github.com/openalgeria/docs'

# Copyright
#copyright: 'Copyright &copy; 2016 - 2017 Martin Donath'

# Configuration
theme:
  name: 'material'
  language: 'fr'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true
# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
